### PR TITLE
Bring back YAML configuration option

### PR DESCRIPTION
**Pull request by turbokongen**

### CODE REVIEW

**Comment by Hellowlol** [comment]
IMO setting up using yaml should never been removed. Im still pretty sure the error is in _check and update method. I can check and make a PR for this.

**Comment by turbokongen** [comment]
> IMO setting up using yaml should never been removed. Im still pretty sure the error is in _check and update method. I can check and make a PR for this.

Sure, no problem. Let's add it back in.

**Comment by turbokongen** [comment]
@Hellowlol 
Can you test this?
I've tested it on my machines, and works as expected.

**Comment by Hellowlol** [comment]
Will do. Btw i think you should change the name in hacs.json i couldnt figure out why i didnt find the integration when i tried to set it up.

**Comment by turbokongen** [comment]
@Hellowlol did this work to your expectations?

**Comment by Hellowlol** [comment]
I havn't got around to test it. Busy with some other HA stuff. Ill test it later to day.

**Pull request merged**
